### ISSUE TITLE
PHP Extension "APCu" Not Installed

### ISSUE THREAD

**Issue by pdhimal1** [bitnami/bitnami-docker-phabricator#78]
Installing the "APCu" PHP extension will improve performance. This extension is strongly recommended. Without it, Phabricator must rely on a very inefficient disk-based cache.

I followed the steps in here https://docs.bitnami.com/virtual-machine/components/php/#how-to-install-the-apcu-module to install APCu on my bitnami phabricator container. 

Added the following to my custom `app-entrypoint.sh`
```
wget https://pecl.php.net/get/apcu-5.1.8.tgz
tar xzf apcu-5.1.8.tgz
cd apcu-5.1.8
phpize
./configure --with-php-config=/opt/bitnami/php/bin/php-config
make
sudo make install
echo "extension=apcu.so" >> /opt/bitnami/php/etc/php.ini
```

I get this PHP warning which tells me that APCu is not configured correctly. 
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/apcu.so' - 
/opt/bitnami/php/lib/php/extensions/apcu.so: cannot open shared object file: No such file or directory in 
Unknown on line 0
```

`PHP Extension "APCu" Not Installed` still shows up as a setup issue on phabricator.

**Comment by pdhimal1** [comment]
Look at this:
```
Installing shared extensions: /opt/bitnami/php/lib/php/extensions/no-debug-non-zts-20160303/
Installing header files:/opt/bitnami/php/include/php/
```
Now look at the warning message:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/bitnami/php/lib/php/extensions/apcu.so' -
 /opt/bitnami/php/lib/php/extensions/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0

```
It looks like the shared extension is being installed in ` /opt/bitnami/php/lib/php/extensions/no-debug-non-zts-20160303/` directory. PHP is trying to load the library from `/opt/bitnami/php/lib/php/extensions/`

Hope this helps

**Comment by chipironcin** [comment]
Hi @pdhimal1 
I have checked and I was able to reproduce and narrow down the issue.

It seems (despite the extensions folder being specified in php.ini) that PHP itself is compiled using the default extension directory `/opt/bitnami/php/lib/php/extensions/no-debug-non-zts-20160303/`.

Due to that, PHP will try to find its extensions in the folder indicated by php.ini but when compiling it will compile extensions for the other default folder.
As a workaround just move the library from `/opt/bitnami/php/lib/php/extensions/no-debug-non-zts-20160303/` to `/opt/bitnami/php/lib/php/extensions/`.

We are working on a fix and will release a PHP revision fixing this issue, and maybe include APCU by default but disabled so Phabricator can easily enable it. Subscribe to this repo to get updates.

**Comment by pdhimal1** [comment]
@chipironcin Thanks for looking at this.
Any updates?

**Comment by chipironcin** [comment]
Hi @pdhimal1 
I filed an internal issue and worked on it for a bit but haven't fixed it yet.
The issue has been bumped, we will try to fix it shortly.

**Comment by pdhimal1** [comment]
@chipironcin  Were you guys able to fix this issue? Updates?

**Comment by juan131** [comment]
Hi @pdhimal1 

We have at task included in our backlog. As the impact of the issue is moderate, there are no immediate plans to work on it. Nevertheless it will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by marcosbc** [comment]
Hi @pdhimal1,

Sorry for the delay on this. We have downloaded the latest Phabricator container, followed the steps below and were unable to reproduce this issue: APCu was properly installed, as it may have been fixed in later versions of our PHP containers.

Please find the exact same steps we followed:

```bash
$ install_packages build-essential autoconf
$ mkdir -p /tmp/apcu && cd /tmp/apcu
$ curl -O https://pecl.php.net/get/apcu-5.1.11.tgz
$ tar xzf apcu-5.1.11.tgz
$ cd apcu-5.1.11
$ phpize
$ ./configure --with-php-config=/opt/bitnami/php/bin/php-config
$ make
$ make install
$ echo "extension=apcu.so" >> /opt/bitnami/php/etc/php.ini
$ php -m | grep -i apcu
apcu
```

Do you get different results? If so, which Phabricator container version are you using? Could you check with the latest version?

Thanks!

**Comment by marcosbc** [comment]
Hi @pdhimal1,

Just wanted to let you know that we released a new revision of the Bitnami Phabricator Docker image, which now includes APCu enabled by default.

The version numbers are 2018.25.0-r6 (Debian) and 2018.25.0-ol-7-r10 (Oracle Linux).

**Comment by adarshaj** [comment]
Can this issue be reopened? I am on 'bitnami/phabricator:2018.32.0-debian-9-r3' image and I still the same isue as @pdhimal1 posted. I cross checked `php -m | grep -i apcu` to be sure that apcu is actually missing..

**Comment by marcosbc** [comment]
Hi @adarshaj, we have reopened this issue until your issue is resolved.

Your issue is really strange, since we ran the following docker-compose setup and everything was correct:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2018.32.0-debian-9-r3'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

After the container started, we were able to confirm that APCu was loaded:

```
$ docker exec apcu_phabricator_1 php -m | grep apcu
apcu
```

With the following command, you will see that APCu exists:

```
$ docker exec apcu_phabricator_1 ls -la /opt/bitnami/php/lib/php/extensions/apcu.so
-rwxr-xr-x 1 root root 98976 Jul 27 10:22 /opt/bitnami/php/lib/php/extensions/apcu.so
```

In addition to the above, when we access that same Phabricator installation's Setup Issues, we don't see any reference to APCu not being installed.

Could you provide more details for reproducing this issue in a clean envirnoment? Could it be possible that you were using an outdated image?

**Comment by adarshaj** [comment]
Oh, I did see docker pull in the image when i changed from `latest` to `2018.32.0-debian-9-r3`, so it may not be issue with the docker image. however, I do have mounted volumes from very old phabricator images.. (that's `/bitnami/phabricator` & `/bitnami/apache`). I will try to reproduce in an isolated environment to be sure. Thanks for reopening!

**Comment by adarshaj** [comment]
@marcosbc - I have the proper docker image on my server with hash `sha256:21767d76e9093e65d31c12a5d15836bcb3d7c1e3913320a9cae65ef1724a0d42`.

But you are right, I can see apcu in a completely isolated new setup. However, I migrated from helm chart setup (on kubernetes) to docker-compose, so to keep things identical, I had two mounts for phabricator image - one at `/bitnami/phabricator` and other at `/bitnami/apache`. There's definitely a difference in startup logs (feel free to download to inspect full):
$ diff [old.log](https://github.com/bitnami/bitnami-docker-phabricator/files/2295533/old.log) [new.log](https://github.com/bitnami/bitnami-docker-phabricator/files/2295536/new.log)
```diff
2c2
< phabricator_1  | apache  INFO  ==> Reconfiguring PID file location...
---
> phabricator_1  | apache  INFO  ==> Patching httpoxy...
9c9,11
< phabricator_1  | phabric INFO  Phabricator has being initialized already, restoring...
---
> phabricator_1  | phabric INFO  Configuring Apache settings...
> phabricator_1  | phabric INFO  Configuring PHP settings...
> phabricator_1  | phabric INFO  Checking connection to database...
12a15,16
> phabricator_1  | phabric INFO  Creating Database...
> phabricator_1  | phabric INFO  Configuring Phabricator...
16,18c20,26
< phabricator_1  | phabric INFO     Persisted data and properties have been restored.
< phabricator_1  | phabric INFO     Any input specified will not take effect.
< phabricator_1  | phabric INFO   This installation requires no credentials.
---
> phabricator_1  | phabric INFO     Host: 127.0.0.1
> phabricator_1  | phabric INFO     First Name: FirstName
> phabricator_1  | phabric INFO     Last Name: LastName
> phabricator_1  | phabric INFO     Username: user
> phabricator_1  | phabric INFO     Password: **********
> phabricator_1  | phabric INFO     Email: user@example.com
> phabricator_1  | phabric INFO   (Passwords are not shown for security reasons)
```

Especially the lines .. `Configuring Apache settings...` and `Configuring PHP settings...`. Can you point towards what may be the issue?

Here's the docker-compose.yml equivalent i use:
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2018.32.0-debian-9-r3'
    ports:
      - '81:80'
      - '8443:443'
    volumes:
      - 'phabricator_data:/bitnami/phabricator'
      - 'apache_data:/bitnami/apache'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
  apache_data:
    driver: local
```

**Comment by adarshaj** [comment]
Ah, I see the problem:
```shell
$ ls -al /opt/bitnami/php

/opt/bitnami/php:
total 8
...
lrwxrwxrwx 1 root   root    17 Aug 16 23:12 conf -> /bitnami/php/conf
...
```

I don't have a mount at /bitnami/php (coming from a very old phabricator image on kubernetes via helm chart)! I think that explains why it wasn't even present in `php -m | grep -i apcu`.

Thanks for indulging me! can be closed again :)

**Comment by marcosbc** [comment]
I'm glad to hear that you got it it fixed!

Closing this ticket again.
