### ISSUE TITLE
Error: Could not connect to SMTP host

### ISSUE THREAD

**Issue by CarLoOSX** [bitnami/bitnami-docker-phabricator#93]
I'm trying to send mails in Phabricator:

The error is : 

EXCEPTION: (PhutilProxyException) Error while executing Task ID 13. {>} (phpmailerException) SMTP Error: Could not connect to SMTP host. at [<phabricator>/externals/phpmailer/class.phpmailer.php:804]
phabricator_1  | [27-Feb-2018 16:34:27 UTC] arcanist(head=stable, ref.stable=8fe1d7701e5d), phabricator(head=stable, ref.stable=3f2419eebb61), phutil(head=stable, ref.stable=03e5605b42e4)
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #0 <#2> PHPMailer::SmtpConnect() called at [<phabricator>/externals/phpmailer/class.phpmailer.php:689]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #1 <#2> PHPMailer::SmtpSend(string, string) called at [<phabricator>/externals/phpmailer/class.phpmailer.php:576]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #2 <#2> PHPMailer::Send() called at [<phabricator>/src/applications/metamta/adapter/PhabricatorMailImplementationPHPMailerAdapter.php:159]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #3 <#2> PhabricatorMailImplementationPHPMailerAdapter::send() called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:605]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #4 <#2> PhabricatorMetaMTAMail::sendWithMailers(array) called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:491]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #5 <#2> PhabricatorMetaMTAMail::sendNow() called at [<phabricator>/src/applications/metamta/PhabricatorMetaMTAWorker.php:22]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #6 <#2> PhabricatorMetaMTAWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:123]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #7 <#2> PhabricatorWorker::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/storage/PhabricatorWorkerActiveTask.php:171]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #8 <#2> PhabricatorWorkerActiveTask::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorTaskmasterDaemon.php:22]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #9 PhabricatorTaskmasterDaemon::run() called at [<phutil>/src/daemon/PhutilDaemon.php:219]
phabricator_1  | [27-Feb-2018 16:34:27 UTC]   #10 PhutilDaemon::execute() called at [<phutil>/scripts/daemon/exec/exec_daemon.php:131]

environment configuration: 

    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=*****@gmail.com
      - SMTP_PASSWORD=******

Any Idea ?

Thank you.

**Comment by tompizmor** [comment]
HI @CarLoOSX,

There was an issue with the SMTP configuration. We have just published the Phabricator 2018.8.0-r1 release solving this issue. 

Would you mind trying again with the latest image and these environment variables?

```
environment:
  - SMTP_HOST=smtp.gmail.com
  - SMTP_PORT=587
  - SMTP_USER=*****@gmail.com
  - SMTP_PASSWORD=******
  - SMTP_PROTOCOL=tls
```

Remember to pull the latest phabricator docker image:

```
$ docker pull bitnami/phabricator:latest
```
 
or alternatively you can use the exact tag in your docker-compose file:

```
image: 'bitnami/phabricator:2018.8.0-r1'
```

**Comment by hazaveh** [comment]
i downloaded "image: 'bitnami/phabricator:2018.8.0-r1'" but im still getting the same error:

`[2018-03-13 10:38:37] EXCEPTION: (phpmailerException) SMTP Error: Could not connect to SMTP host. at [<phabricator>/externals/phpmailer/class.phpmailer.php:804]
arcanist(head=stable, ref.stable=8fe1d7701e5d), phabricator(head=stable, ref.stable=3f2419eebb61), phutil(head=stable, ref.stable=03e5605b42e4)
  #0 PHPMailer::SmtpConnect() called at [<phabricator>/externals/phpmailer/class.phpmailer.php:689]
  #1 PHPMailer::SmtpSend(string, string) called at [<phabricator>/externals/phpmailer/class.phpmailer.php:576]
  #2 PHPMailer::Send() called at [<phabricator>/src/applications/metamta/adapter/PhabricatorMailImplementationPHPMailerAdapter.php:159]
  #3 PhabricatorMailImplementationPHPMailerAdapter::send() called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:605]
  #4 PhabricatorMetaMTAMail::sendWithMailers(array) called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:491]
  #5 PhabricatorMetaMTAMail::sendNow() called at [<phabricator>/src/applications/metamta/PhabricatorMetaMTAWorker.php:22]
  #6 PhabricatorMetaMTAWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:123]
  #7 PhabricatorWorker::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:162]
  #8 PhabricatorWorker::scheduleTask(string, integer, array) called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:467]
  #9 PhabricatorMetaMTAMail::save() called at [<phabricator>/src/applications/metamta/management/PhabricatorMailManagementSendTestWorkflow.php:193]
  #10 PhabricatorMailManagementSendTestWorkflow::execute(PhutilArgumentParser) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:441]
  #11 PhutilArgumentParser::parseWorkflowsFull(array) called at [<phutil>/src/parser/argument/PhutilArgumentParser.php:333]
  #12 PhutilArgumentParser::parseWorkflows(array) called at [<phabricator>/scripts/mail/manage_mail.php:21]`

any advise?

**Comment by CarLoOSX** [comment]
mmm... After update the image I got this working... But I deleted all data releated to this container. Try to delete volumes and containers in docker to make a clean test.

**Comment by hazaveh** [comment]
Ouch I can't afford that. I just migrate a ton of stuff to this instance. Any easier way instead of going through all the migration process? My guys are actively using the phabricator

**Comment by juan131** [comment]
Hi @hazaveh 

We developed very recently a tool to detect SMTP issues:

https://github.com/bitnami-labs/healthcheck-tools/tree/master/cmd/smtp-checker

You can use it inside your container with your SMTP credentials:

```
./smtp-checker -smtp_host <SMTP HOST> -smtp_port <SMTP PORT> -smtp_user <SMTP USER> -smtp_password <SMTP PASSWORD> -mail_recipient <YOUR_MAIL_ACCOUNT>
```

Substituting the placeholders with the values you set on your environment:

```
environment:
  - SMTP_HOST=smtp.gmail.com
  - SMTP_PORT=587
  - SMTP_USER=*****@gmail.com
  - SMTP_PASSWORD=******
```

Then share the output of running the tool with us.
